export const features = [
  {
    name: "Tempo (BPM)",
    isNumberInput: true,
    options: {
      min: 60,
      max: 255,
      placeholder: "Enter BPM",
      step: 1,
    },
  },
  {
    name: "Key Signature",
    isDropdown: true,
    value: "keySignature",
    options: [
      "C",
      "Cm",
      "C#",
      "C#m",
      "D",
      "Dm",
      "D#",
      "D#m",
      "E",
      "Em",
      "F",
      "Fm",
      "F#",
      "F#m",
      "G",
      "Gm",
      "G#",
      "G#m",
      "A",
      "Am",
      "A#",
      "A#m",
      "B",
      "Bm",
    ],
  },
  {
    name: "Genre",
    isDropdown: true,
    value: "genre",
    options: [
      "Afrobeats",
      "Afrohouse",
      "Amapiano",
      "Boom Bap",
      "Cloud Trap",
      "Dancehall",
      "Drill",
      "Drum & Bass",
      "Dubstep",
      "EDM",
      "Funk",
      "Hip Hop",
      "Hood Trap",
      "House",
      "Jazz",
      "Lo-fi",
      "Pop",
      "Reggae",
      "RnB",
      "RnB Drill",
      "Soul",
      "Techno",
      "Trap",
    ],
  },
];
