services:
  beatblock-api:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DB=${SQL_DB}
      - SQL_SERVER=${SQL_SERVER}
      - SQL_PORT=${SQL_PORT}
      - AZURITE_CONNECTION_STRING=${AZURITE_CONNECTION_STRING}
    depends_on:
      - sqlserver
    networks:
      - beatblock

  beatblock-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - beatblock-api
    networks:
      - beatblock
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "${SQL_PORT}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SQL_PASSWORD}" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - beatblock
  
  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./db/sql/init:/sql
    command: >
      /bin/bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${SQL_PASSWORD} -C -i /sql/CreateDatabase.sql;
      '
    networks:
      - beatblock

  flyway:
    image: flyway/flyway:9-alpine
    depends_on:
      db-init:
        condition: service_completed_successfully
    entrypoint: ["flyway", "-url=jdbc:sqlserver://sqlserver:${SQL_PORT};databaseName=${SQL_DB};trustServerCertificate=true", "-user=sa", "-password=${SQL_PASSWORD}", "migrate"] 
    volumes:
      - ./db/sql/migrations:/flyway/sql
    networks:
      - beatblock

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNozJeWz0uG2fFtqS/fA1sJbGZ1Q2z2VGHkAZd0pYxkAzj6Cc==
    command: ["azurite-blob", "--blobHost", "0.0.0.0", "--silent"]
    networks:
      - beatblock

volumes:
  sqlserver_data:
  azurite_data:

networks:
  beatblock:
