CREATE TABLE [Project] (
  Id INT PRIMARY KEY IDENTITY(1,1),
  Name VARCHAR(50) NOT NULL,
  Description VARCHAR(100),
  KeySignature VARCHAR(4),
  Bpm TINYINT,
  Genre VARCHAR(50),
  Daw VARCHAR(50) NOT NULL,
  FilesUrl VARCHAR(1000) NOT NULL,
  AudioUrl VARCHAR(1000),
  ArtworkUrl VARCHAR(1000),
  CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);