CREATE TABLE [Project] (
  Id INT PRIMARY KEY IDENTITY(1,1),
  Name VARCHAR(50) NOT NULL,
  Description VARCHAR(100),
  KeySignature VARCHAR(4),
  Bpm TINYINT,
  Genre VARCHAR(50),
  Daw VARCHAR(50) NOT NULL,
  FilePath VARCHAR(255) NOT NULL,
  AudioPath VARCHAR(255),
  ImagePath VARCHAR(255),
  CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);

CREATE TABLE [User] (
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  FirstName VARCHAR(20) NOT NULL,
  LastName VARCHAR(20) NOT NULL,
  Alias VARCHAR(20),
  Email VARCHAR(320) NOT NULL,
  Password VARCHAR(60) NOT NULL,
  CONSTRAINT UQ_Users_Email UNIQUE (Email)
);