services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SQL_PASSWORD}" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  
  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./sql/init:/sql
    command: >
      /bin/bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${SQL_PASSWORD} -C -i /sql/CreateDatabase.sql;
      '

  flyway:
    image: flyway/flyway:9-alpine
    depends_on:
      db-init:
        condition: service_completed_successfully
    entrypoint: ["flyway", "-url=jdbc:sqlserver://host.docker.internal:1433;databaseName=BeatBlock;trustServerCertificate=true", "-user=sa", "-password=${SQL_PASSWORD}", "migrate"] 
    volumes:
      - ./sql/migrations:/flyway/sql

volumes:
  sqlserver_data: