name: Run Unit Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Run Back-end Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use user-local .NET SDK
        run: |
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend/backend

      - name: Build solution
        run: dotnet build --no-restore --configuration Release
        working-directory: backend/backend

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: backend/backend
